  ### What is TensofFlow?

  TensorFlow is an open-source end-to-end machine learning libarary for preprocessing data, modelling data and serving models (getting them into the hands of others).


  ### Why use TensorFLow?

  Rather than building machine learning and deep learning models from scratch, it's more likely you'll use a library such as TensorFlow. This sib ecause it contains many of the most common machine laerning functions you'll want to use

  ### What we're goint to conver

  TensorFlow is vast. But the main premise is ismple: turn data into numbers (tensors) and build machine learning algorithms to find patterns in them

In this notebook we cover some ot the most fundamental TensorFlow opearions, more specificially:
- Introduction to tensors (creating tensors)
- Getting information from tensors (tensor attributes)
- Manipulating tensors (tensor opearations)
- Tensors and Numpy
- Using @tf.function (a way to speed up your regular Python functions)
- Exercises to try


In [ ]:
# crate timestamp
import datetime

print(f"Notebook last run (end-to-end) : {datetime.datetime.now()}")

Notebook last run (end-to-end) : 2025-05-20 11:16:53.189419


### Infroduction to Tensors

If you've ever used Numpy, tensros are kind of like Numpy arrays ( we';; see more on  this later) <br>
for the sake of this notebook and going forward, you can think of a tensos as a multi-dimensinal numberical representation ( also referred to as n-dimensional, where n cna be any number) of something. Where something can be almost anything you can imagine:
- It could be numbers themselves ( using tensors to represent the price of houses).
- It could be an image ( using tensors to represent the pixels of an image)
-It could be text ( using tensors to represent words).
- Or it could be some other form of information (or data) you wnat to represnet with numbers.

The main difference between tensors and NumPy arrays (also an n-dimensinal array of numbers) is that tensors can ve used on GPUs (grphical processing usnits) and TPUs (tensor processing Units).<br>

The benefit of veing able to run on FPUs and TPUs is faster computation, this means, if we wnated to find apatterns in the numerical representations of our data, we can generally find them faster using GPUs and TPUs.<br>





In [ ]:
# Import TensorFlos
import tensorflow as tf
print(tf.__version__) # find the version number

2.18.0


### Creating Tensors with tf.constant()

As mentioned before, in general, you usually won't created tensors yourself. This is becuase TensorFlos has Modules buil-in (such as tg.io and tf. data) which are able to read your data sources and automatically conver them to tensors and then later on, neural network models will process these for use.
<br>

But for now, becuase we're getting familar with tensors themselves and yhow to manipulate them, we'll see how we can create them ourselves.

In [ ]:
# create a scalar (rank 0 tensor)
scalar = tf.constant(7)
scalar

<tf.Tensor: shape=(), dtype=int32, numpy=7>

A scalar is know as a rank 0 tensor. Becuase it has no dimensions (it's just a number)
> **Note** : for now, you don't need to know too much about the different ranks of tensors (but we will wee more on this later). Them important point is knowing tnesors can have an ulimited range of diemsions ( the exact amount will depend on what data you're representing).



In [ ]:
# check the number of dimensions of a tensor ( ndim stands for number of dimenstions)
scalar.ndim

0

In [ ]:
# create a vector (more thant 0 dimensions)
vector = tf.constant([10,10])
vector

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10, 10], dtype=int32)>

In [11]:
# create a matrix (more than 1 dimension)
matrix = tf.constant([[10, 7],
                      [7,10]])
matrix

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 7, 10]], dtype=int32)>

In [12]:
matrix.ndim

2

By default, TensorFlow creates tensors with either and int32 of float32 datatype.<br>
This is known as 32-bit precisiion (the higher the number, the more precise the nubmer, the more space it takes up on your computer)


In [13]:
# Create another matrix and detatype
another_matrix = tf.constant([[10., 7.],
                              [3.,2.],
                              [8., 9.]], dtype=tf.float16) # specify the data type with 'dtype'
another_matrix

<tf.Tensor: shape=(3, 2), dtype=float16, numpy=
array([[10.,  7.],
       [ 3.,  2.],
       [ 8.,  9.]], dtype=float16)>

In [15]:
# Even though another_matrix contains more numbers, its dimensions stay the same
another_matrix.ndim

2

In [22]:
# How about a tensor? (more than 2 dimesions, alothough, all of the above items are also technically tensors)
tensor = tf.constant([[[1,2,3],
                       [4,5,6]],
                      [[7,8,9],
                       [10,11,12]],
                      [[13,14,15],
                       [16,17,18]]])
tensor

<tf.Tensor: shape=(3, 2, 3), dtype=int32, numpy=
array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [16, 17, 18]]], dtype=int32)>

In [24]:
tensor.ndim

3

This is know as a rank 3 tensor (3-dimensions), however a tensor can have an arbitrary (unlimited) amount of dimensions.<br>
For example, you might turn a series of images into tensors with shape (224, 224, 3,32), where :
- 224, 224 ( the first 2 dimensions) are the height and width of the images in pixels.
- 3 is the number of colour channels of the image (red, green, blue).
- 32 is the batch size ( the number of images a neural network sees at any one tiem).

All ot the above variables we've created are actually tensors. But you may also hear them referred to as their different names (the ones we gave them)
<br>
<br>
- scalar : a single number.
- vector : a number with direction (e.g. wind speed with direction).
- matrix : a 2-dimensional array of numbers.
-tensor: an n-dimensional array of numbers ( where n can be any number, a 0-dimension tensor is a scalar, a 1-dimension tensor is a vector).



###  Creating Tensors with tf.Variable()

You acan also (altough you likely rarely will, becuase often, when working with data, tensors are created for you automatically) create tensors using ```tf.Variable()```.<br>
The difference between tf.Variable() and tf.constant() is tensors create with tf.constant() are immutable (can't be chanbed, can only be used to create a new tensor), where as, tensors with tf.variable() are mutable (can be changed).

In [28]:
# Create the same tenso with tf.Variable() and tf.constant()
changeable_tensor = tf.Variable([10, 7])
unchangeable_tensor = tf.constant([10, 7])
changeable_tensor, unchangeable_tensor

(<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([10,  7], dtype=int32)>,
 <tf.Tensor: shape=(2,), dtype=int32, numpy=array([10,  7], dtype=int32)>)

In [30]:
# will error ( requires the .assign() method)
changeable_tensor[0] = 7
changeable_tensor

TypeError: 'ResourceVariable' object does not support item assignment

To chage an elementof a tf.Vatiable() tensors requires the assign() method.

In [33]:
# won't error
changeable_tensor[0].assign(7)
changeable_tensor

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([7, 7], dtype=int32)>

In [36]:
# will error (can't chage tf. constat())
unchangeable_tensor[0].assign(7)
unchangeable_tensor

AttributeError: 'tensorflow.python.framework.ops.EagerTensor' object has no attribute 'assign'

Which one should you use?<br>
```tf.constant()``` or ```tf.Variable()```
It will depend on what your problem requires. However, most of the time, TensorFlow will automatically choose for you (when loading data or modelling data).